debug: true
log:
  dir: ./logs
  stdOut: true
  Error: ./logs/error
  Info: ./logs/info

httpServer:
  dialTimeout: "30s"
  dialKeepalive: "30s"
  maxIdleConn: 100
  maxIdle_conns_per_host: 100
  max_conns_per_host: 200
  idle_conn_timeout: "90s"
  tls_handshake_timeout: "10s"
  expect_continue_timeout: "1s"
mysql:
    dsn: "root:111111@tcp(192.168.1.8:3306)/xxblog?charset=utf8&parseTime=True&loc=Local"
    maxIdleConnection: 10
    maxConnection: 500
    maxLifeTime: "300s"

redis:
  network: "tcp"
  addr: "127.0.0.1:6379"
  auth: ""
  db: 0
  maxIdleConnection: 10
  maxConnection: 100
  pubSubChan: "linkPK:chan:local"
init:
  db: true

